version: '2.2'
services:
  # =================== APP ===================
  handling:
    image: microdb/benchmark:handling
    ports:
      - '8080'
    environment:
      - MYSQL_HOST=dataorigin
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
      - DB_DEFAULTS=false
      - NATS_HOST=nats
      - NATS_PORT=4222
      - NATS_CLIENT_ID=handlingd-client-1
      - NATS_CLUSTER_ID=nats-cluster
    command: --database microdb
    networks:
      - benchmark
    depends_on:
      - publisher-1
      - publisher-2
      - publisher-3
      - querier-cargos
      - querier-carrier-movements
      - querier-deliveries
      - querier-handling-activities
      - querier-handling-events
      - querier-handling-histories
      - querier-itineraries
      - querier-legs
      - querier-locations
      - querier-route-specifications
      - querier-schedules
      - querier-voyages
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.handling.rule=PathPrefix(`/handling`)"
      - "traefik.http.routers.handling.entrypoints=web"

  booking-1:
    image: microdb/benchmark:booking
    ports:
      - '8080'
    environment:
      - MYSQL_HOST=dataorigin
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
      - DB_DEFAULTS=false
      - NATS_HOST=nats
      - NATS_PORT=4222
      - NATS_CLIENT_ID=bookingd-client-1
      - NATS_CLUSTER_ID=nats-cluster
    command: --database microdb
    networks:
      - benchmark
    restart: unless-stopped
    depends_on:
      - publisher-1
      - publisher-2
      - publisher-3
      - querier-cargos
      - querier-carrier-movements
      - querier-deliveries
      - querier-handling-activities
      - querier-handling-events
      - querier-handling-histories
      - querier-itineraries
      - querier-legs
      - querier-locations
      - querier-route-specifications
      - querier-schedules
      - querier-voyages   
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.booking.rule=PathPrefix(`/booking`)"
      - "traefik.http.routers.booking.entrypoints=web"
      
  booking-2:
    image: microdb/benchmark:booking
    ports:
      - '8080'
    environment:
      - MYSQL_HOST=dataorigin
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
      - DB_DEFAULTS=false
      - NATS_HOST=nats
      - NATS_PORT=4222
      - NATS_CLIENT_ID=bookingd-client-2
      - NATS_CLUSTER_ID=nats-cluster
    command: --database microdb
    networks:
      - benchmark
    restart: unless-stopped
    depends_on:
      - publisher-1
      - publisher-2
      - publisher-3
      - querier-cargos
      - querier-carrier-movements
      - querier-deliveries
      - querier-handling-activities
      - querier-handling-events
      - querier-handling-histories
      - querier-itineraries
      - querier-legs
      - querier-locations
      - querier-route-specifications
      - querier-schedules
      - querier-voyages
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.booking.rule=PathPrefix(`/booking`)"
      - "traefik.http.routers.booking.entrypoints=web"

  booking-3:
    image: microdb/benchmark:booking
    ports:
      - '8080'
    environment:
      - MYSQL_HOST=dataorigin
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
      - DB_DEFAULTS=false
      - NATS_HOST=nats
      - NATS_PORT=4222
      - NATS_CLIENT_ID=bookingd-client-3
      - NATS_CLUSTER_ID=nats-cluster
    command: --database microdb
    networks:
      - benchmark
    restart: unless-stopped
    depends_on:
      - publisher-1
      - publisher-2
      - publisher-3
      - querier-cargos
      - querier-carrier-movements
      - querier-deliveries
      - querier-handling-activities
      - querier-handling-events
      - querier-handling-histories
      - querier-itineraries
      - querier-legs
      - querier-locations
      - querier-route-specifications
      - querier-schedules
      - querier-voyages
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.booking.rule=PathPrefix(`/booking`)"
      - "traefik.http.routers.booking.entrypoints=web"
      
  booking-4:
    image: microdb/benchmark:booking
    ports:
      - '8080'
    environment:
      - MYSQL_HOST=dataorigin
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
      - DB_DEFAULTS=false
      - NATS_HOST=nats
      - NATS_PORT=4222
      - NATS_CLIENT_ID=bookingd-client-4
      - NATS_CLUSTER_ID=nats-cluster
    command: --database microdb
    networks:
      - benchmark
    restart: unless-stopped
    depends_on:
      - publisher-1
      - publisher-2
      - publisher-3
      - querier-cargos
      - querier-carrier-movements
      - querier-deliveries
      - querier-handling-activities
      - querier-handling-events
      - querier-handling-histories
      - querier-itineraries
      - querier-legs
      - querier-locations
      - querier-route-specifications
      - querier-schedules
      - querier-voyages
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.booking.rule=PathPrefix(`/booking`)"
      - "traefik.http.routers.booking.entrypoints=web"

  booking-5:
    image: microdb/benchmark:booking
    ports:
      - '8080'
    environment:
      - MYSQL_HOST=dataorigin
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
      - DB_DEFAULTS=false
      - NATS_HOST=nats
      - NATS_PORT=4222
      - NATS_CLIENT_ID=bookingd-client-5
      - NATS_CLUSTER_ID=nats-cluster
    command: --database microdb
    networks:
      - benchmark
    restart: unless-stopped
    depends_on:
      - publisher-1
      - publisher-2
      - publisher-3
      - querier-cargos
      - querier-carrier-movements
      - querier-deliveries
      - querier-handling-activities
      - querier-handling-events
      - querier-handling-histories
      - querier-itineraries
      - querier-legs
      - querier-locations
      - querier-route-specifications
      - querier-schedules
      - querier-voyages
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.booking.rule=PathPrefix(`/booking`)"
      - "traefik.http.routers.booking.entrypoints=web"

  tracking-1:
    image: microdb/benchmark:tracking
    ports:
      - '8080'
    environment:
      - MYSQL_HOST=dataorigin
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
      - DB_DEFAULTS=false
      - NATS_HOST=nats
      - NATS_PORT=4222
      - NATS_CLIENT_ID=trackingd-client-1
      - NATS_CLUSTER_ID=nats-cluster
    command: --database microdb
    networks:
      - benchmark
    restart: unless-stopped
    depends_on:
      - publisher-1
      - publisher-2
      - publisher-3
      - querier-cargos
      - querier-carrier-movements
      - querier-deliveries
      - querier-handling-activities
      - querier-handling-events
      - querier-handling-histories
      - querier-itineraries
      - querier-legs
      - querier-locations
      - querier-route-specifications
      - querier-schedules
      - querier-voyages
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tracking.rule=PathPrefix(`/tracking`)"
      - "traefik.http.routers.tracking.entrypoints=web"

  tracking-2:
    image: microdb/benchmark:tracking
    ports:
      - '8080'
    environment:
      - MYSQL_HOST=dataorigin
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
      - DB_DEFAULTS=false
      - NATS_HOST=nats
      - NATS_PORT=4222
      - NATS_CLIENT_ID=trackingd-client-2
      - NATS_CLUSTER_ID=nats-cluster
    command: --database microdb
    networks:
      - benchmark
    restart: unless-stopped
    depends_on:
      - publisher-1
      - publisher-2
      - publisher-3
      - querier-cargos
      - querier-carrier-movements
      - querier-deliveries
      - querier-handling-activities
      - querier-handling-events
      - querier-handling-histories
      - querier-itineraries
      - querier-legs
      - querier-locations
      - querier-route-specifications
      - querier-schedules
      - querier-voyages
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tracking.rule=PathPrefix(`/tracking`)"
      - "traefik.http.routers.tracking.entrypoints=web"

  tracking-3:
    image: microdb/benchmark:tracking
    ports:
      - '8080'
    environment:
      - MYSQL_HOST=dataorigin
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
      - DB_DEFAULTS=false
      - NATS_HOST=nats
      - NATS_PORT=4222
      - NATS_CLIENT_ID=trackingd-client-3
      - NATS_CLUSTER_ID=nats-cluster
    command: --database microdb
    networks:
      - benchmark
    restart: unless-stopped
    depends_on:
      - publisher-1
      - publisher-2
      - publisher-3
      - querier-cargos
      - querier-carrier-movements
      - querier-deliveries
      - querier-handling-activities
      - querier-handling-events
      - querier-handling-histories
      - querier-itineraries
      - querier-legs
      - querier-locations
      - querier-route-specifications
      - querier-schedules
      - querier-voyages
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tracking.rule=PathPrefix(`/tracking`)"
      - "traefik.http.routers.tracking.entrypoints=web"

  tracking-4:
    image: microdb/benchmark:tracking
    ports:
      - '8080'
    environment:
      - MYSQL_HOST=dataorigin
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
      - DB_DEFAULTS=false
      - NATS_HOST=nats
      - NATS_PORT=4222
      - NATS_CLIENT_ID=trackingd-client-4
      - NATS_CLUSTER_ID=nats-cluster
    command: --database microdb
    networks:
      - benchmark
    restart: unless-stopped
    depends_on:
      - publisher-1
      - publisher-2
      - publisher-3
      - querier-cargos
      - querier-carrier-movements
      - querier-deliveries
      - querier-handling-activities
      - querier-handling-events
      - querier-handling-histories
      - querier-itineraries
      - querier-legs
      - querier-locations
      - querier-route-specifications
      - querier-schedules
      - querier-voyages
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tracking.rule=PathPrefix(`/tracking`)"
      - "traefik.http.routers.tracking.entrypoints=web"

  tracking-5:
    image: microdb/benchmark:tracking
    ports:
      - '8080'
    environment:
      - MYSQL_HOST=dataorigin
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
      - DB_DEFAULTS=false
      - NATS_HOST=nats
      - NATS_PORT=4222
      - NATS_CLIENT_ID=trackingd-client-5
      - NATS_CLUSTER_ID=nats-cluster
    command: --database microdb
    networks:
      - benchmark
    restart: unless-stopped
    depends_on:
      - publisher-1
      - publisher-2
      - publisher-3
      - querier-cargos
      - querier-carrier-movements
      - querier-deliveries
      - querier-handling-activities
      - querier-handling-events
      - querier-handling-histories
      - querier-itineraries
      - querier-legs
      - querier-locations
      - querier-route-specifications
      - querier-schedules
      - querier-voyages
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tracking.rule=PathPrefix(`/tracking`)"
      - "traefik.http.routers.tracking.entrypoints=web"

  # ================ PUBLISHER ================
  publisher-1:
    image: microdb/benchmark:publisher
    environment:
      - MYSQL_HOST=dataorigin
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_TABLES=voyages,carrier_movements,schedules,locations
      - DB_DEFAULTS=false
      - NATS_HOST=nats
      - NATS_PORT=4222
      - NATS_CLUSTER_ID=nats-cluster
      - PUBLISHER_ID=11
      - DATAORIGIN_CFG=/dataorigin.yaml
    networks:
      benchmark:

  publisher-2:
    image: microdb/benchmark:publisher
    environment:
      - MYSQL_HOST=dataorigin
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_TABLES=cargos,handling_histories,handling_events,handling_activities
      - DB_DEFAULTS=false
      - NATS_HOST=nats
      - NATS_PORT=4222
      - NATS_CLUSTER_ID=nats-cluster
      - PUBLISHER_ID=15
      - DATAORIGIN_CFG=/dataorigin.yaml
    networks:
      benchmark:

  publisher-3:
    image: microdb/benchmark:publisher
    environment:
      - MYSQL_HOST=dataorigin
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_TABLES=route_specifications,itineraries,deliveries,legs
      - DB_DEFAULTS=false
      - NATS_HOST=nats
      - NATS_PORT=4222
      - NATS_CLUSTER_ID=nats-cluster
      - PUBLISHER_ID=19
      - DATAORIGIN_CFG=/dataorigin.yaml
    networks:
      benchmark:

  # ================= QUERIER =================
  querier-voyages:
    image: microdb/benchmark:querier
    environment:
      - MYSQL_HOST=dataorigin
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_TABLE=voyages
      - DB_DEFAULTS=false
      - NATS_HOST=nats
      - NATS_PORT=4222
      - NATS_CLIENT_ID=voyages-querier
      - NATS_CLUSTER_ID=nats-cluster
      - DATAORIGIN_CFG=/dataorigin.yaml
    networks:
      benchmark:
  
  querier-carrier-movements:
    image: microdb/benchmark:querier
    environment:
      - MYSQL_HOST=dataorigin
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_TABLE=carrier_movements
      - DB_DEFAULTS=false
      - NATS_HOST=nats
      - NATS_PORT=4222
      - NATS_CLIENT_ID=carrier-movements-querier
      - NATS_CLUSTER_ID=nats-cluster
      - DATAORIGIN_CFG=/dataorigin.yaml
    networks:
      benchmark:
  
  querier-schedules:
    image: microdb/benchmark:querier
    environment:
      - MYSQL_HOST=dataorigin
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_TABLE=schedules
      - DB_DEFAULTS=false
      - NATS_HOST=nats
      - NATS_PORT=4222
      - NATS_CLIENT_ID=schedules-querier
      - NATS_CLUSTER_ID=nats-cluster
      - DATAORIGIN_CFG=/dataorigin.yaml
    networks:
      benchmark:
  
  querier-locations:
    image: microdb/benchmark:querier
    environment:
      - MYSQL_HOST=dataorigin
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_TABLE=locations
      - DB_DEFAULTS=false
      - NATS_HOST=nats
      - NATS_PORT=4222
      - NATS_CLIENT_ID=locations-querier
      - NATS_CLUSTER_ID=nats-cluster
      - DATAORIGIN_CFG=/dataorigin.yaml
    networks:
      benchmark:
  
  querier-cargos:
    image: microdb/benchmark:querier
    environment:
      - MYSQL_HOST=dataorigin
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_TABLE=cargos
      - DB_DEFAULTS=false
      - NATS_HOST=nats
      - NATS_PORT=4222
      - NATS_CLIENT_ID=cargos-querier
      - NATS_CLUSTER_ID=nats-cluster
      - DATAORIGIN_CFG=/dataorigin.yaml
    networks:
      benchmark:
  
  querier-handling-histories:
    image: microdb/benchmark:querier
    environment:
      - MYSQL_HOST=dataorigin
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_TABLE=handling_histories
      - DB_DEFAULTS=false
      - NATS_HOST=nats
      - NATS_PORT=4222
      - NATS_CLIENT_ID=handling_histories-querier
      - NATS_CLUSTER_ID=nats-cluster
      - DATAORIGIN_CFG=/dataorigin.yaml
    networks:
      benchmark:
  
  querier-handling-events:
    image: microdb/benchmark:querier
    environment:
      - MYSQL_HOST=dataorigin
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_TABLE=handling_events
      - DB_DEFAULTS=false
      - NATS_HOST=nats
      - NATS_PORT=4222
      - NATS_CLIENT_ID=handling_events-querier
      - NATS_CLUSTER_ID=nats-cluster
      - DATAORIGIN_CFG=/dataorigin.yaml
    networks:
      benchmark:
  
  querier-handling-activities:
    image: microdb/benchmark:querier
    environment:
      - MYSQL_HOST=dataorigin
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_TABLE=handling_activities
      - DB_DEFAULTS=false
      - NATS_HOST=nats
      - NATS_PORT=4222
      - NATS_CLIENT_ID=handling_activities-querier
      - NATS_CLUSTER_ID=nats-cluster
      - DATAORIGIN_CFG=/dataorigin.yaml
    networks:
      benchmark:
  
  querier-route-specifications:
    image: microdb/benchmark:querier
    environment:
      - MYSQL_HOST=dataorigin
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_TABLE=route_specifications
      - DB_DEFAULTS=false
      - NATS_HOST=nats
      - NATS_PORT=4222
      - NATS_CLIENT_ID=route_specifications-querier
      - NATS_CLUSTER_ID=nats-cluster
      - DATAORIGIN_CFG=/dataorigin.yaml
    networks:
      benchmark:
  
  querier-itineraries:
    image: microdb/benchmark:querier
    environment:
      - MYSQL_HOST=dataorigin
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_TABLE=itineraries
      - DB_DEFAULTS=false
      - NATS_HOST=nats
      - NATS_PORT=4222
      - NATS_CLIENT_ID=itineraries-querier
      - NATS_CLUSTER_ID=nats-cluster
      - DATAORIGIN_CFG=/dataorigin.yaml
    networks:
      benchmark:
  
  querier-deliveries:
    image: microdb/benchmark:querier
    environment:
      - MYSQL_HOST=dataorigin
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_TABLE=deliveries
      - DB_DEFAULTS=false
      - NATS_HOST=nats
      - NATS_PORT=4222
      - NATS_CLIENT_ID=deliveries-querier
      - NATS_CLUSTER_ID=nats-cluster
      - DATAORIGIN_CFG=/dataorigin.yaml
    networks:
      benchmark:
  
  querier-legs:
    image: microdb/benchmark:querier
    environment:
      - MYSQL_HOST=dataorigin
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_TABLE=legs
      - DB_DEFAULTS=false
      - NATS_HOST=nats
      - NATS_PORT=4222
      - NATS_CLIENT_ID=legs-querier
      - NATS_CLUSTER_ID=nats-cluster
      - DATAORIGIN_CFG=/dataorigin.yaml
    networks:
      benchmark:

  # ================= GATEWAY =================
  gateway:
    image: "traefik:v2.4"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8080:80"
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - benchmark

networks:
  benchmark:
    external:
      name: backend_benchmark
