version: '2.2'
services:
  # ================ DATASTORE ================
  mysql-master:
    image: microdb/benchmark:mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
    cpu_count: 4
    mem_limit: 4gb
    oom_kill_disable: true
    networks:
      - benchmark

networks:
  benchmark:
    external:
      name: backend_benchmark
